In [30]:
import numpy as np 
a=np.array([1, 2, 3, 4, 5])
print(a)
b=a.tolist()
print(b)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [44]:
import numpy as np
m = np.arange(6).reshape(3,2)
print(m)
print(np.trace(m))


[[0 1]
 [2 3]
 [4 5]]
3


In [11]:
import numpy as np
a = np.array([[1,4],[5,3],[4,7]])
for z in range(a.shape[0]):
    for x in a[z,:]:
        if x>=4:
            print(x)

4
5
4
7


In [102]:
import numpy as np
a = np.array([[1,4],[5,3],[4,7]])
b = np.array([[7,3],[2,6],[1,1]])
c = np.add(a,b)
print(c)

[[8 7]
 [7 9]
 [5 8]]


In [10]:
import numpy as np
z = np.array([[1,4,8],[5,3,9],[4,7,8]])
result = 0
for i in range(z.shape[0]):
    c = np.mean(-z[i])
    result = c + result
print(result)

(3, 3)
-16.333333333333332
